WINDOW_WIDTH = 960
WINDOW_HEIGHT = 720
SCALE_FACTOR = 3
FPS_CAP = 60
MAX_SOUND_CHANNELS = 16
TITLE = "Paradigm Engine v0.0.1"

#Components
C_POSITION = 0
C_VELOCITY = 1
C_IMAGE = 2
C_INPUT_CONTROLLER = 3
C_VELOCITY_INPUT = 4